name: acenup_icons_flutter
description: A new Flutter plugin project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: AcenupIconsFlutter
      fonts:
        - asset: lib/fonts/AcenupIconsFlutter.ttf
          weight: 400
